{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.jaemyeong.SDSMealAPI\/documentation\/SwiftSoup\/Exception\/Error-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.jaemyeong.SDSMealAPI\/documentation\/SwiftSoup\/Exception\/localizedDescription"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"SwiftSoup"}],"role":"collectionGroup","title":"Error Implementations"},"hierarchy":{"paths":[["doc:\/\/com.jaemyeong.SDSMealAPI\/documentation\/SwiftSoup","doc:\/\/com.jaemyeong.SDSMealAPI\/documentation\/SwiftSoup\/Exception"]]},"references":{"doc://com.jaemyeong.SDSMealAPI/documentation/SwiftSoup/Exception":{"role":"symbol","title":"Exception","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Exception"}],"abstract":[],"identifier":"doc:\/\/com.jaemyeong.SDSMealAPI\/documentation\/SwiftSoup\/Exception","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Exception"}],"url":"\/documentation\/swiftsoup\/exception"},"doc://com.jaemyeong.SDSMealAPI/documentation/SwiftSoup/Exception/localizedDescription":{"role":"symbol","title":"localizedDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.jaemyeong.SDSMealAPI\/documentation\/SwiftSoup\/Exception\/localizedDescription","kind":"symbol","type":"topic","url":"\/documentation\/swiftsoup\/exception\/localizeddescription"},"doc://com.jaemyeong.SDSMealAPI/documentation/SwiftSoup":{"role":"collection","title":"SwiftSoup","abstract":[],"identifier":"doc:\/\/com.jaemyeong.SDSMealAPI\/documentation\/SwiftSoup","kind":"symbol","type":"topic","url":"\/documentation\/swiftsoup"}}}